version: '2'

# Note: use the database service name `db` in the Host IP Address field ...
# Or, `docker container inspect {postgrescontainerid}` to obtain the IP Address needed for completing the Drupal setup screen.

services:
  # Postgres
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  # Drupal
  cms:
    image: drupal:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - cms_modules:/var/www/html/modules
      - cms_profiles:/var/www/html/profiles
      - cms_themes:/var/www/html/themes
      - cms_sites:/var/www/html/sites
    depends_on:
      - db
  
# Volumes
volumes:
  db_data:
  cms_modules:
  cms_profiles:
  cms_themes:
  cms_sites:
